#!/usr/bin/env python
"""A simple script to add a target for followup to the observation database."""

import os
import sys

import astropy.units as u
from astropy.coordinates import SkyCoord
from astropy.time import Time

from gototile.grid import SkyGrid

import numpy as np

import obsdb as db


def run(name, target_ra, target_dec):
    """Add an Mpointing with 5 60s L filter exposures."""
    with db.open_session() as session:
        # Find the current Grid in the database
        db_grids = session.query(db.Grid).all()
        if not db_grids:
            raise ValueError('No defined grids found!')
        else:
            # Might have multiple grids defined, just take the latest...
            db_grid = db_grids[-1]

        # Create a SkyGrid from the database Grid
        fov = {'ra': db_grid.ra_fov * u.deg, 'dec': db_grid.dec_fov * u.deg}
        overlap = {'ra': db_grid.ra_overlap, 'dec': db_grid.dec_overlap}
        grid = SkyGrid(fov, overlap, kind=db_grid.algorithm)

        coord = SkyCoord(target_ra * u.deg, target_dec * u.deg)
        sep = np.array(coord.separation(grid.coords))
        tile_index = np.where(sep == (min(sep)))[0][0]
        tile_name = grid.tilenames[tile_index]

        # Find the matching GridTile
        query = session.query(db.GridTile)
        query = query.filter(db.GridTile.grid == db_grid,
                             db.GridTile.name == tile_name)
        db_grid_tile = query.one_or_none()
        if not db_grid_tile:
            raise ValueError('Cannot find tile in the database')

        print('Using grid {} tile {}: ra={:.4f}, dec={:.4f}'.format(db_grid.name,
                                                                    db_grid_tile.name,
                                                                    db_grid_tile.ra,
                                                                    db_grid_tile.dec,
                                                                    ))

        # Get the User, or make it if it doesn't exist
        try:
            user = db.get_user(session, username='goto')
        except ValueError:
            print('ERROR: No database user found')
            return

        # Get Mpointing and ExposureSet data
        expsets = [{'num_exp': 5,
                    'exptime': 60,
                    'filt': 'L',
                    'binning': 1,
                    'imgtype': 'SCIENCE',
                    },
                   ]

        mp_data = {'object_name': name,
                   'too': 0,
                   'start_rank': 0,
                   'num_todo': 1,
                   'valid_time': -1,
                   'wait_time': 12 * 60,
                   'start_time': str(Time.now()),
                   'stop_time': str(Time.now() + 1 * u.day),
                   'min_alt': 30,
                   'max_sunalt': -15,
                   'max_moon': 'B',
                   'min_moonsep': 30,
                   'min_time': 450,  # (60+30)*5
                   }

        # Create database enteries
        db_mpointing = db.Mpointing(**mp_data, user=user)
        db_mpointing.grid_tile = db_grid_tile
        for exp_data in expsets:
            db_exposure_set = db.ExposureSet(**exp_data)
            db_mpointing.exposure_sets.append(db_exposure_set)

        # Create the first Pointing (i.e. preempt the caretaker)
        # Note need to add objects, get_next_pointing uses IDs but they don't have them yet!
        db_pointing = db_mpointing.get_next_pointing()
        db_pointing.grid_tile = db_grid_tile
        db_mpointing.pointings.append(db_pointing)

        # Add to database
        db.insert_items(session, [db_mpointing])

        # Print for debugging
        print('Added to database:')
        session.refresh(db_mpointing)
        print(db_mpointing)
        for db_exposure_set in db_mpointing.exposure_sets:
            print(db_exposure_set)


if __name__ == '__main__':
    args = sys.argv[1:]
    if len(args) != 3:
        print('Add a single pointing with 5 60s L exposures')
        print('Usage: {} <name> <ra> <dec>'.format(os.path.basename(__file__)))
        print(' (<ra> and <dec> should be in decimal degrees)')
        sys.exit()

    # Target name
    name = args[0]

    # RA
    try:
        ra = float(args[1])
        assert 0 <= ra < 360
    except Exception:
        print('Invalid RA, must be in decimal degrees')
        sys.exit()

    # Dec
    try:
        dec = float(args[2])
        assert -90 < dec < 90
    except Exception:
        print('Invalid Dec, must be in decimal degrees')
        sys.exit()

    # Run main program
    run(name, ra, dec)
