#!/usr/bin/env python
"""A script add a survey of defined points into the G-TeCS database."""

import argparse
import getpass
import time

import obsdb as db


MP_SETTINGS = dict(minAlt=35,
                   minTime=(60 + 5) * 3,
                   maxSunAlt=-12,
                   maxMoon='B',
                   minMoonSep=50,
                   ToO=0,
                   num_todo=-1,
                   valid_time=-1,
                   wait_time=4320,  # 3 days
                   )

EXP_SETTINGS = dict(expTime=60,
                    raoff=0.,
                    decoff=0.,
                    numexp=3,
                    typeFlag='SCIENCE',
                    filt='L',
                    binning=1,
                    utMask=None)


def get_userkey(username, description=''):
    """Get user key of a user, and create it if it doesn't exit."""
    with db.open_session() as session:
        try:
            user_key = db.get_userkey(session, username)
        except Exception:
            # Create user if it doesn't exist
            prompt = "Creating {} user - give password: ".format(username)
            passwd = getpass.getpass(prompt=prompt)
            db.add_user(session, username, passwd, description)
            session.commit()
            user_key = db.get_userkey(session, username)
    return user_key


def get_coords_from_file(filename):
    """Define mini-survey tiles centres and ranks."""
    allras = []
    alldecs = []
    ranks = []
    names = []
    with open(filename) as file:
        for i, line in enumerate(file):
            if line[0] == '#':
                continue
            tile, ra, dec, *_ = line.split()
            if i > 800:
                break
            rank = (i - 1) // 100 + 990
            name = 'Galaxy_survey_{}'.format(tile)

            print(name, ra, dec, rank)

            allras.append(ra)
            alldecs.append(dec)
            ranks.append(rank)
            names.append(name)

    return allras, alldecs, ranks, names


def run(filename):
    """Create the mpointings and add them to the database."""
    # Create the tile centres
    ras, decs, ranks, names = get_coords_from_file(filename)

    # Add to the database
    mpointings = []
    user_key = get_userkey('goto', 'GOTO Survey')
    with db.open_session() as session:
        # create Mpointings
        print('Creating mpointings...')
        start = time.time()
        for ra, dec, rank, name in zip(ras, decs, ranks, names):
            mp = db.Mpointing(userKey=user_key,
                              objectName=name,
                              ra=float(ra),
                              decl=float(dec),
                              start_rank=rank,
                              **MP_SETTINGS)

            mp.exposure_sets.append(db.ExposureSet(**EXP_SETTINGS))
            mpointings.append(mp)
        print('  took {:.2f} secs'.format(time.time() - start))

        print('Adding {} mpointings to database...'.format(len(mpointings)))
        start = time.time()
        db.insert_items(session, mpointings)
        print('  took {:.2f} secs'.format(time.time() - start))


if __name__ == '__main__':
    description = """Create a mini-survey around a given centre."""

    parser = argparse.ArgumentParser(description=description,
                                     formatter_class=argparse.ArgumentDefaultsHelpFormatter)

    parser.add_argument('file', help="File with tiles", type=str)

    args = parser.parse_args()

    filename = args.file

    run(filename)
